apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app-deployment
  labels:
    app: next-app
spec:
  replicas: 3  # Number of pods to run (adjust as needed)
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
        - name: next-app
          image: 127.0.0.1:15000/kube-demo-v1  # Replace with your actual Docker image name
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: next-app-service
spec:
  selector:
    app: next-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # You can change this to ClusterIP or NodePort depending on your needs
